### PR TITLE
Dashboard popup

### PR DESCRIPTION
**Pull request by halenander**
Related to #10

### CODE REVIEW

**Review by frienderman2 — APPROVED** [review]
Looks all good to me

**Comment by JacksonCrawford** [comment]
**Bug**: The first time that the dashboard is called after the cluster has been created, it gets a 503 error ('no endpoints available for service "kubernetes-dashboard"') as the page is opened before the dashboard can be fully loaded. After a second, a refresh is enough to get it going again, but I would recommend adding a check for a successful dashboard generation before sending the user to the page.

**Comment by JacksonCrawford** [comment]
**Feature Request**: Keep the present in the terminal output in case the user closes the tab and doesn't want to rerun the command to get it back.

**Comment by JacksonCrawford** [comment]
Looks good.

**Review by JacksonCrawford — COMMENTED** [review]
Looks good

**Comment by JacksonCrawford** [comment]
Accidentally closed because I'm illiterate

**Review by JacksonCrawford — APPROVED** [review]
Looks good (last time haha)

**Pull request merged**
