### PR TITLE
Kubeaudit

### PR DESCRIPTION
**Pull request by JacksonCrawford**
Please review kubeaudit functionality, along with new helper methods in pkg/king/cluster_utils.go

### CODE REVIEW

**Review by halenander — COMMENTED** [review]
I believe some changes still need to be made if the cluster is empty- this error message appears in that case:
panic: runtime error: index out of range [124] with length 124

**Comment by JacksonCrawford** [comment]
> I believe some changes still need to be made if the cluster is empty- this error message appears in that case: panic: runtime error: index out of range [124] with length 124

Which file and line # is this occurring in?

**Comment by halenander** [comment]
> > I believe some changes still need to be made if the cluster is empty- this error message appears in that case: panic: runtime error: index out of range [124] with length 124
> 
> Which file and line # is this occurring in?

Somehow it seems to work now? I'll approve the merge

**Review by halenander — APPROVED** [review]
Seems to work as intended now

**Review by frienderman2 — APPROVED** [review]
Shes a beaut

**Pull request merged**
