### PR TITLE
Dashboard popup

### PR DESCRIPTION
**Pull request by halenander**
Finishing up copying and popup functionality. Added xclip and pbcopy to test dependencies test. Possible further work may be needed for multithreading website initiation and popup (so there is no/less delay).

### CODE REVIEW

**Comment by JacksonCrawford** [comment]
Could you add an independent check for pbcopy/xclip in `startup_test.go` that is based on OS? pbcopy is not available on Linux and vice-versa.

**Comment by JacksonCrawford** [comment]
Otherwise dashboard looks great!

**Review by JacksonCrawford — APPROVED** [review]
Works great on Linux!

**Review by frienderman2 — APPROVED** [review]
Seems good

**Pull request merged**
