### PR TITLE
Audit fix

### PR DESCRIPTION
**Pull request by JacksonCrawford**
This branch implements the following fixes to kubeaudit functionality:

- Only audits namespace
- Creates a cluster-admin clusterrolebinding for kubeaudit

There are also some minor changes including:

- Changing redis' pod name to sbom-cache
- Reworking `GetPodsStruct` and `CreateRoles`
- Updating dependencies to be more accurate

### CODE REVIEW

**Comment by halenander** [comment]
Can you switch the order of the handling of the -severity and the -reconfigure flags?

**Comment by JacksonCrawford** [comment]
> Can you switch the order of the handling of the -severity and the -reconfigure flags?

Why?

**Comment by halenander** [comment]
> > Can you switch the order of the handling of the -severity and the -reconfigure flags?
> 
> Why?

So that we can run both flags in one command

**Review by halenander — APPROVED** [review]
Works great! Bugs in testing seem to have been fixed

**Review by frienderman2 — APPROVED** [review]
Works for me

**Pull request merged**
